# Generated by Django 5.0.6 on 2024-07-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_full_name', models.CharField(max_length=255)),
                ('how_mail', models.EmailField(max_length=100)),
                ('hod_contact', models.CharField(max_length=15)),
                ('hod_image', models.ImageField(blank=True, null=True, upload_to='images/profile_Images/')),
                ('hod_department', models.CharField(max_length=15)),
                ('hod_address', models.TextField(max_length=1000)),
                ('project_tittle', models.CharField(max_length=100)),
                ('project_duration', models.CharField(max_length=100)),
                ('project_budget', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Status')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportmetrix.user')),
            ],
            options={
                'verbose_name': 'AddProject',
                'verbose_name_plural': 'AddProject',
            },
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
