# Generated by Django 5.0.6 on 2024-07-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0002_addproject_delete_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='uid',
        ),
    ]
