# Generated by Django 5.0.6 on 2024-07-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0003_remove_addproject_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='hod_department',
            field=models.CharField(max_length=100),
        ),
    ]
