# Generated by Django 5.0.6 on 2024-07-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0004_alter_addproject_hod_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='how_mail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
