# Generated by Django 5.0.6 on 2024-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0005_alter_addproject_how_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
