# Generated by Django 5.0.6 on 2024-07-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportmetrix', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='hod_image',
        ),
    ]
